name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    name: Build and test
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Firebird
      run: |
        sudo apt install firebird3.0-server -y
        sudo cp attic/firebird.conf /etc/firebird/3.0
        sudo systemctl restart firebird3.0
        sudo chmod 0664 /etc/firebird/3.0/SYSDBA.password
        grep '=' /etc/firebird/3.0/SYSDBA.password |sed 's/^/export /' >test_user.env
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.12.2' # Define the elixir version [required]
        otp-version: '24.2' # Define the OTP version [required]
        experimental-otp: true
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: |
        source test_user.env
        mix test
